/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homemanager.app;

import homemanager.list.LinkedList;

import static homemanager.utilities.StringUtils.join;
import static homemanager.utilities.StringUtils.split;
import static homemanager.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
