/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("homemanager.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("homemanager.app.AppKt")
}
