/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homemanager.app

import homemanager.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
